### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by ndonkoHenri** [saurabhwadekar/flet_route#1]
Hey! Nice Package.
Please add more documentation in the README.
Detailed documentation for each parameter, each class and/or function. 
It is very important for those using a package!

**Comment by saurabhwadekar** [comment]
yes i am working on it.
thank you for your suggestion

**Comment by saurabhwadekar** [comment]
Hey brother can you tell by looking at me again.
Whether it is made right or not.

Because I do not know English, it becomes very difficult for me.
🙏

**Comment by ndonkoHenri** [comment]
You added necessary points. Good! 
Also add those new informations in the docstrings, so people don't have to always open your repo to be documented. 

By the way, your repo was mentioned in the Flet Discord: https://discord.com/channels/981374556059086931/1084213730511958096

**Comment by saurabhwadekar** [comment]
thank you so much brother
