### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by move123456789** [saurabhwadekar/flet_route#4]
I don't know if async is supported, i have tryed but have not managed to get it to work. If its not supported will it be sometime in the future?

**Comment by saurabhwadekar** [comment]
Yes, asynchronous support will be available in the upcoming release.

**Comment by saurabhwadekar** [comment]
If flet-route has worked for you, don't forget to star it. it cheers up

**Comment by move123456789** [comment]
I will

**Comment by move123456789** [comment]
I saw you added async support 😁 Thank you, when will new pypi package be released?

**Comment by saurabhwadekar** [comment]
after doing some tests

**Comment by move123456789** [comment]
Okay, nice i packed it myself and tested it out, it works perfect for me so far

**Comment by saurabhwadekar** [comment]
I am thinking of releasing it with a cli tool

**Comment by move123456789** [comment]
Okay, will it still work with static flet website then? https://flet.dev/docs/guides/python/publishing-static-website/
right now i can just write flet-route in my requirements.txt and it will micropip install the package in the pyodide enviroment and it works perfect

**Comment by saurabhwadekar** [comment]
There will be no changes in the original package. Just add cli packages to it separately

**Comment by move123456789** [comment]
Okay, nice

**Comment by saurabhwadekar** [comment]
You can install flet-route 0.3.0 from pypi

**Comment by move123456789** [comment]
Nice :D
